// Change in state of an object is called as event;
// button events
// submit events
// mouse events
// keyboard events 

// events can be generated by user interactions;





// Get the button element
const button = document.getElementById('myButton');

// Add an event listener for the 'click' event
button.addEventListener('click', function() {
  alert('Button Clicked!');
});




const button2 = document.getElementById('myButton');

function handleClick() {
  alert('Button Clicked!');
  // Remove event listener after one click
  button2.removeEventListener('click', handleClick);
}

// Add event listener
button2.addEventListener('click', handleClick);
